name: python-app-actions

on:
  push:
    branches:
      - 'main'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: test application
      run: make test
  
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: faitht/testrepo:pythonApp-githubActions
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
      - uses: actions/checkout@v3
      - name: Chmod
        run: chmod 400 $SSH_KEY
      - name: Login to droplet 
        run: ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@64.225.97.100 "
               docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
               docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"

